name: Deploy static site

on:
  push:
    branches: [ "main" ]

concurrency:
  group: deploy-openfloodgauge
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_PATH: /var/www/openfloodgauge
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          # Strict host key checking with prefetch
          ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" -H "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts

      - name: Upload release (rsync)
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ secrets.SSH_PORT || 22 }}
        run: |
          RELEASE="${DEPLOY_PATH}/releases/${GITHUB_SHA}"
          rsync -az --delete \
            --exclude ".git" \
            --exclude ".github" \
            -e "ssh -i ~/.ssh/id_ed25519 -p ${SSH_PORT}" \
            ./ "${SSH_USER}@${SSH_HOST}:${RELEASE}/"

      - name: Activate release & reload nginx
        env:
            SSH_USER: ${{ secrets.SSH_USER }}
            SSH_HOST: ${{ secrets.SSH_HOST }}
            SSH_PORT: ${{ secrets.SSH_PORT || '22' }}
        run: |
            ssh -i ~/.ssh/id_ed25519 -p "${SSH_PORT}" "${SSH_USER}@${SSH_HOST}" <<EOF
            set -euo pipefail
            DEPLOY_PATH="/var/www/openfloodgauge"
            RELEASE="${DEPLOY_PATH}/releases/${GITHUB_SHA}"
            chown -R www-data:www-data "${RELEASE}"
            find "${RELEASE}" -type d -exec chmod 755 {} \;
            find "${RELEASE}" -type f -exec chmod 644 {} \;
            ln -sfn "${RELEASE}" "${DEPLOY_PATH}/current"
            ls -dt "${DEPLOY_PATH}/releases"/* | tail -n +6 | xargs -r rm -rf --
            nginx -t
            systemctl reload nginx
            EOF
